name: Kindian
description: |
    Concrete5.7 CMS for buidling easy and beautiful websites
version: v0.1
category: Salalem
maintainer: Salalem Learning <tech@salalem.com>
projectURL: http://www.opensaas.com.au
