version: '2'
services:
  mqtt:
    image: ncarlier/mqtt:latest
    stdin_open: true
    network_mode: host
    tty: true
    ports:
    - 1883:1883/tcp
    labels:
      io.rancher.container.pull_image: always