version: '2'
catalog:
  name: "Home Assistant"
  version: "0.60"
  description: "Home Assistant is an open-source home automation platform running on Python 3"
  questions:
    - variable: "privileged"
      description: | 
        Enable/disable to run in privileged mode (Must be true to access USB Insteon/ZWave/Zigbee devices).
      label: "Privileged mode:"
      required: true
      default: false 
      type: "boolean"
    - variable: "config_path"
      label: "Config path"
      description: |
        The host location of your Home Assistant config files
      type: "string"
      default: "/opt/homeassistant"
      required: true
services:
  home-assistant:
    scale: 1
    start_on_create: true